import 'dart:io';

import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../../../core/config/app_config.dart';
import '../../../../shared/models/transaction_model.dart';
import '../../domain/export_report_style.dart';

class PdfExportService {

  Future<File>
      generateMonthlyReport({

    required String
        reportTitle,

    required String
        currencySymbol,

    required List<
            TransactionModel>
        transactions,

    required double income,

    required double expense,

    required double balance,

    required ExportReportStyle
        style,
  })
  async {

    // =====================================================
    // LOAD FONTS
    // =====================================================

    final regularFont =
        pw.Font.ttf(

      await rootBundle.load(
        'assets/fonts/NotoSans-Regular.ttf',
      ),
    );

    final boldFont =
        pw.Font.ttf(

      await rootBundle.load(
        'assets/fonts/NotoSans-Bold.ttf',
      ),
    );

    // =====================================================
    // PDF DOCUMENT
    // =====================================================

    final pdf =
        pw.Document(

      theme: pw.ThemeData.withFont(

        base: regularFont,

        bold: boldFont,
      ),
    );

    final generatedDate =
        DateTime.now();

    final savingsRate =
        income <= 0

            ? 0.0

            : ((balance / income) *
                    100)
                .clamp(
              0,
              100,
            );

    // =====================================================
    // ADD PAGE
    // =====================================================

    pdf.addPage(

      pw.MultiPage(

        pageFormat:
            PdfPageFormat.a4,

        margin:
            const pw.EdgeInsets.all(
          32,
        ),

        footer:
            (context) {

          return pw.Container(

            margin:
                const pw.EdgeInsets.only(
              top: 16,
            ),

            child: pw.Row(

              mainAxisAlignment:
                  pw.MainAxisAlignment
                      .spaceBetween,

              children: [

                pw.Text(

                  'Generated on '
                  '${generatedDate.day}/'
                  '${generatedDate.month}/'
                  '${generatedDate.year}',

                  style:
                      const pw.TextStyle(

                    fontSize: 10,

                    color:
                        PdfColors.grey,
                  ),
                ),

                pw.Text(

                  'Generated by '
                  '${AppConfig.companyName}',

                  style:
                      const pw.TextStyle(

                    fontSize: 10,

                    color:
                        PdfColors.grey,
                  ),
                ),
              ],
            ),
          );
        },

        build: (context) {

          if (
            style ==
            ExportReportStyle
                .classic
          ) {

            return _buildClassicReport(

              reportTitle:
                  reportTitle,

              currencySymbol:
                  currencySymbol,

              transactions:
                  transactions,

              income: income,

              expense: expense,

              balance: balance,
            );
          }

          return _buildModernReport(

            reportTitle:
                reportTitle,

            currencySymbol:
                currencySymbol,

            transactions:
                transactions,

            income: income,

            expense: expense,

            balance: balance,

            savingsRate:
                savingsRate.toDouble(),
          );
        },
      ),
    );

    // =====================================================
    // SAVE FILE
    // =====================================================

    final dir =
        await getTemporaryDirectory();

    final file = File(
      '${dir.path}/finance_report.pdf',
    );

    await file.writeAsBytes(
      await pdf.save(),
    );

    return file;
  }

  // =======================================================
  // CLASSIC REPORT
  // =======================================================

  List<pw.Widget>
      _buildClassicReport({

    required String
        reportTitle,

    required String
        currencySymbol,

    required List<
            TransactionModel>
        transactions,

    required double income,

    required double expense,

    required double balance,
  }) {

    return [

      pw.Text(

        reportTitle,

        style:
            pw.TextStyle(

          fontSize: 28,

          fontWeight:
              pw.FontWeight.bold,
        ),
      ),

      pw.SizedBox(
        height: 8,
      ),

      pw.Text(
        AppConfig.appName,
      ),

      pw.SizedBox(
        height: 24,
      ),

      pw.Container(

        padding:
            const pw.EdgeInsets.all(
          16,
        ),

        decoration:
            pw.BoxDecoration(

          border:
              pw.Border.all(
            color:
                PdfColors.grey400,
          ),
        ),

        child: pw.Column(

          crossAxisAlignment:
              pw.CrossAxisAlignment
                  .start,

          children: [

            pw.Text(

              'Financial Summary',

              style:
                  pw.TextStyle(

                fontWeight:
                    pw.FontWeight.bold,

                fontSize: 18,
              ),
            ),

            pw.SizedBox(
              height: 12,
            ),

            pw.Text(
              'Income: $currencySymbol ${income.toStringAsFixed(2)}',
            ),

            pw.Text(
              'Expense: $currencySymbol ${expense.toStringAsFixed(2)}',
            ),

            pw.Text(
              'Balance: $currencySymbol ${balance.toStringAsFixed(2)}',
            ),
          ],
        ),
      ),

      pw.SizedBox(
        height: 28,
      ),

      pw.Text(

        'Transactions',

        style:
            pw.TextStyle(

          fontSize: 20,

          fontWeight:
              pw.FontWeight.bold,
        ),
      ),

      pw.SizedBox(
        height: 12,
      ),

      _transactionsTable(
        transactions:
            transactions,

        currencySymbol:
            currencySymbol,
      ),
    ];
  }

  // =======================================================
  // MODERN REPORT
  // =======================================================

  List<pw.Widget>
      _buildModernReport({

    required String
        reportTitle,

    required String
        currencySymbol,

    required List<
            TransactionModel>
        transactions,

    required double income,

    required double expense,

    required double balance,

    required double
        savingsRate,
  }) {

    return [

      // =============================================
      // HEADER
      // =============================================

      pw.Container(

        padding:
            const pw.EdgeInsets.only(
          bottom: 20,
        ),

        child: pw.Column(

          crossAxisAlignment:
              pw.CrossAxisAlignment
                  .start,

          children: [

            pw.Text(

              reportTitle,

              style:
                  pw.TextStyle(

                fontSize: 28,

                fontWeight:
                    pw.FontWeight.bold,
              ),
            ),

            pw.SizedBox(
              height: 6,
            ),

            pw.Text(

              AppConfig.appName,

              style:
                  const pw.TextStyle(

                fontSize: 14,

                color:
                    PdfColors.grey700,
              ),
            ),
          ],
        ),
      ),

      pw.Divider(
        color:
            PdfColors.grey300,
      ),

      pw.SizedBox(
        height: 24,
      ),

      // =============================================
      // SUMMARY
      // =============================================

      pw.Text(

        'Financial Summary',

        style:
            pw.TextStyle(

          fontSize: 22,

          fontWeight:
              pw.FontWeight.bold,
        ),
      ),

      pw.SizedBox(
        height: 20,
      ),

      pw.Row(

        mainAxisAlignment:
            pw.MainAxisAlignment
                .spaceBetween,

        children: [

          _summaryCard(

            title: 'Income',

            amount: income,

            color:
                PdfColors.green,

            symbol: '+',

            currencySymbol:
                currencySymbol,
          ),

          _summaryCard(

            title: 'Expense',

            amount: expense,

            color:
                PdfColors.red,

            symbol: '-',

            currencySymbol:
                currencySymbol,
          ),

          _summaryCard(

            title: 'Balance',

            amount: balance,

            color:
                balance >= 0

                    ? PdfColors.blue

                    : PdfColors.orange,

            symbol: '=',

            currencySymbol:
                currencySymbol,
          ),
        ],
      ),

      pw.SizedBox(
        height: 28,
      ),

      // =============================================
      // SAVINGS RATE
      // =============================================

      pw.Container(

        padding:
            const pw.EdgeInsets.all(
          16,
        ),

        decoration:
            pw.BoxDecoration(

          border:
              pw.Border.all(
            color:
                PdfColors.grey300,
          ),
        ),

        child: pw.Column(

          crossAxisAlignment:
              pw.CrossAxisAlignment
                  .start,

          children: [

            pw.Text(

              'Savings Rate',

              style:
                  pw.TextStyle(

                fontWeight:
                    pw.FontWeight.bold,

                fontSize: 16,
              ),
            ),

            pw.SizedBox(
              height: 10,
            ),

            pw.Text(
              '${savingsRate.toStringAsFixed(1)}%',
            ),
          ],
        ),
      ),

      pw.SizedBox(
        height: 28,
      ),

      pw.Text(

        'Transactions',

        style:
            pw.TextStyle(

          fontSize: 22,

          fontWeight:
              pw.FontWeight.bold,
        ),
      ),

      pw.SizedBox(
        height: 16,
      ),

      _transactionsTable(
        transactions:
            transactions,

        currencySymbol:
            currencySymbol,
      ),
    ];
  }

  // =======================================================
  // TRANSACTIONS TABLE
  // =======================================================

  pw.Widget _transactionsTable({

    required List<
            TransactionModel>
        transactions,

    required String
        currencySymbol,
  }) {

    return pw.Table(

      border:
          pw.TableBorder.all(
        color:
            PdfColors.grey300,
      ),

      columnWidths: {

        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(2),
        2: const pw.FlexColumnWidth(2),
        3: const pw.FlexColumnWidth(4),
      },

      children: [

        pw.TableRow(

          decoration:
              const pw.BoxDecoration(

            color:
                PdfColors.grey200,
          ),

          children: [

            _tableHeader(
              'Date',
            ),

            _tableHeader(
              'Type',
            ),

            _tableHeader(
              'Amount',
            ),

            _tableHeader(
              'Notes',
            ),
          ],
        ),

        ...transactions.map(

          (t) {

            final amount =
                t.amount / 100;

            return pw.TableRow(

              children: [

                _tableCell(

                  '${t.transactionDate.day}/'
                  '${t.transactionDate.month}/'
                  '${t.transactionDate.year}',
                ),

                _tableCell(
                  t.type,
                ),

                _tableCell(

                  '$currencySymbol '
                  '${amount.toStringAsFixed(2)}',
                ),

                _tableCell(
                  t.notes ?? '',
                ),
              ],
            );
          },
        ),
      ],
    );
  }

  // =======================================================
  // SUMMARY CARD
  // =======================================================

  pw.Widget _summaryCard({

    required String title,

    required double amount,

    required PdfColor color,

    required String symbol,

    required String currencySymbol,
  }) {

    return pw.Container(

      width: 150,

      padding:
          const pw.EdgeInsets.all(
        16,
      ),

      decoration:
          pw.BoxDecoration(

        border:
            pw.Border.all(

          color: color,

          width: 1.5,
        ),
      ),

      child: pw.Column(

        crossAxisAlignment:
            pw.CrossAxisAlignment
                .start,

        children: [

          pw.Text(

            symbol,

            style:
                pw.TextStyle(

              color: color,

              fontSize: 20,

              fontWeight:
                  pw.FontWeight.bold,
            ),
          ),

          pw.SizedBox(
            height: 12,
          ),

          pw.Text(

            title,

            style:
                pw.TextStyle(

              fontSize: 14,

              fontWeight:
                  pw.FontWeight.bold,
            ),
          ),

          pw.SizedBox(
            height: 6,
          ),

          pw.Text(

            '$currencySymbol '
            '${amount.toStringAsFixed(2)}',

            style:
                pw.TextStyle(

              fontSize: 16,

              color: color,

              fontWeight:
                  pw.FontWeight.bold,
            ),
          ),
        ],
      ),
    );
  }

  // =======================================================
  // TABLE HEADER
  // =======================================================

  pw.Widget _tableHeader(
    String text,
  ) {

    return pw.Padding(

      padding:
          const pw.EdgeInsets.all(
        10,
      ),

      child: pw.Text(

        text,

        style:
            pw.TextStyle(

          fontWeight:
              pw.FontWeight.bold,
        ),
      ),
    );
  }

  // =======================================================
  // TABLE CELL
  // =======================================================

  pw.Widget _tableCell(
    String text,
  ) {

    return pw.Padding(

      padding:
          const pw.EdgeInsets.all(
        10,
      ),

      child: pw.Text(
        text,
      ),
    );
  }
}