import 'package:flutter/material.dart';

import '../../../../core/constants/app_constants.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'Privacy Policy',
        ),
      ),

      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),

        child: Column(
          crossAxisAlignment:
              CrossAxisAlignment.start,

          children: [
            Text(
              'Privacy Policy',
              style: theme.textTheme.headlineMedium?.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),

            const SizedBox(
              height: 8,
            ),

            Text(
              '${AppConstants.appName} • '
              'Version ${AppConstants.appVersion}',
              style: theme.textTheme.bodyMedium?.copyWith(
                color: theme.colorScheme.onSurfaceVariant,
              ),
            ),

            const SizedBox(
              height: 24,
            ),

            _PolicySection(
              title: '1. Introduction',
              content:
                  '${AppConstants.appName} is a personal finance '
                  'management application developed by '
                  '${AppConstants.appCompanyName}. '
                  'This Privacy Policy explains how information '
                  'is handled when you use the application.',
            ),

            _PolicySection(
              title: '2. Financial Information',
              content:
                  'The application allows you to enter and manage '
                  'financial information such as income, expenses, '
                  'accounts, categories, budgets, financial goals, '
                  'investments, and recurring transactions. '
                  'This information is stored locally on your device '
                  'for use within the application.',
            ),

            _PolicySection(
              title: '3. Local Storage',
              content:
                  'Financial information is stored locally on your '
                  'device using the application database. '
                  '${AppConstants.appCompanyName} does not currently '
                  'operate a cloud synchronization service for this '
                  'information and the application does not require '
                  'an account or login to use its core functionality.',
            ),

            _PolicySection(
              title: '4. Device Authentication',
              content:
                  '${AppConstants.appName} may use your device\'s '
                  'biometric authentication or device passcode to '
                  'protect access to the application. '
                  'The application does not receive or store your '
                  'fingerprint, face data, PIN, password, or other '
                  'biometric credentials. Authentication is handled '
                  'by the operating system.',
            ),

            _PolicySection(
              title: '5. Notifications',
              content:
                  'The application may create local notifications '
                  'for features such as financial reminders, '
                  'recurring transactions, and budget alerts. '
                  'These notifications are generated by the '
                  'application on your device.',
            ),

            _PolicySection(
              title: '6. Backup, Export and Sharing',
              content:
                  '${AppConstants.appName} provides user-initiated '
                  'backup and export functionality. Depending on '
                  'the feature used, financial information may be '
                  'exported to files such as JSON, CSV, or PDF. '
                  'When you choose to share an exported file using '
                  'your device\'s sharing functionality, the file '
                  'may be transferred to an application or service '
                  'you select. The handling of that information is '
                  'then subject to the privacy policy of the '
                  'selected third-party application or service.',
            ),

            _PolicySection(
              title: '7. Network Connectivity',
              content:
                  'The application may check the device\'s network '
                  'connectivity status to determine whether the '
                  'device is connected to a network. This information '
                  'is used for application functionality and does '
                  'not mean that your financial records are uploaded '
                  'to our servers.',
            ),

            _PolicySection(
              title: '8. Data Sharing',
              content:
                  '${AppConstants.appName} does not currently '
                  'require users to upload their financial records '
                  'to ${AppConstants.appCompanyName} servers. '
                  'The application does not currently provide cloud '
                  'synchronization of financial records.',
            ),

            _PolicySection(
              title: '9. Data Security',
              content:
                  'We aim to protect information stored by the '
                  'application through the security mechanisms '
                  'provided by the device and the application. '
                  'Users should also protect their device using a '
                  'secure screen lock and should avoid sharing '
                  'exported backup files with untrusted parties.',
            ),

            _PolicySection(
              title: '10. Data Retention and Deletion',
              content:
                  'Because financial records are stored locally, '
                  'they remain on the device until they are deleted '
                  'through the application, removed as part of an '
                  'application data reset, or the application is '
                  'uninstalled. Exported backup files are separate '
                  'files and remain wherever the user has saved or '
                  'shared them.',
            ),

            _PolicySection(
              title: '11. Children\'s Privacy',
              content:
                  '${AppConstants.appName} is intended for general '
                  'personal financial management and is not designed '
                  'specifically for children. We do not knowingly '
                  'collect personal information from children through '
                  'a server-based account system.',
            ),

            _PolicySection(
              title: '12. Changes to This Privacy Policy',
              content:
                  'This Privacy Policy may be updated when the '
                  'application\'s functionality, data handling, or '
                  'services change. The latest version will be made '
                  'available through the application or the relevant '
                  'company website.',
            ),

            _PolicySection(
              title: '13. Contact Us',
              content:
                  'If you have questions, concerns, or need support '
                  'regarding privacy or the application, please '
                  'contact ${AppConstants.appCompanyName}.',
            ),

            const SizedBox(
              height: 8,
            ),

            if (AppConstants.appSupportEmail.isNotEmpty)
              Card(
                child: ListTile(
                  leading: Icon(
                    Icons.email_outlined,
                    color: theme.colorScheme.primary,
                  ),
                  title: const Text(
                    'Support Email',
                  ),
                  subtitle: Text(
                    AppConstants.appSupportEmail,
                  ),
                ),
              ),

            const SizedBox(
              height: 12,
            ),

            Text(
              AppConstants.appCompanyName,
              style: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),

            const SizedBox(
              height: 4,
            ),

            Text(
              AppConstants.appCompanyWebsite,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: theme.colorScheme.onSurfaceVariant,
              ),
            ),

            const SizedBox(
              height: 32,
            ),

            Center(
              child: Text(
                'Last updated: ${DateTime.now().year}',
                style: theme.textTheme.bodySmall?.copyWith(
                  color: theme.colorScheme.onSurfaceVariant,
                ),
              ),
            ),

            const SizedBox(
              height: 60,
            ),
          ],
        ),
      ),
    );
  }
}

class _PolicySection extends StatelessWidget {
  final String title;
  final String content;

  const _PolicySection({
    required this.title,
    required this.content,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Padding(
      padding: const EdgeInsets.only(
        bottom: 24,
      ),

      child: Column(
        crossAxisAlignment:
            CrossAxisAlignment.start,

        children: [
          Text(
            title,
            style: theme.textTheme.titleLarge?.copyWith(
              fontWeight: FontWeight.bold,
            ),
          ),

          const SizedBox(
            height: 8,
          ),

          Text(
            content,
            textAlign: TextAlign.justify,
            style: theme.textTheme.bodyLarge?.copyWith(
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }
}